// app.quicktype.io para tipar 
// vsc extension parse json to 
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CharInfo{
  id:       number;
  name:     string;
  status:   string;
  species:  string;
  type:     string;
  gender:   string;
  origin:   Detail;
  location: Detail;
  image:    string;
  episode:  string[];
  url:      string;
  created:  string;
}

interface Detail {
  name: string;
  url:  string;
}

export const defChar:CharInfo = {
  id: 0,
  name:   '',
  status:   '',
  species:   '',
  type:   '',
  gender:   '',
  image:   '',
  url:   '',
  created:   '',
  origin:   {
    name: '',
    url: '',
  },
  location:   {
    name: '',
    url: '',
  },
  episode:   [],
}
//  

// Generated by https://quicktype.io

export interface EpisodeInfo {
  id:         number;
  name:       string;
  air_date:   string;
  episode:    string;
  characters: string[];
  url:        string;
  created:    string;
}
